image: repo.splunk.com/splunk_at_splunk/sas-golang:1.16.2

stages:
  - release

before_script:
  - cp $NETRC_FILE ~/.netrc

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - goreleaser release --rm-dist
