image: golang:latest

stages:
  - test
  - release

before_script:
  - cp $NETRC_FILE ~/.netrc
  - GOPRIVATE=cd.splunkdev.com go get

lint:
  stage: test
  script:
    - gofmt -l .
    - test -z $(gofmt -l .)
    - go get -u golang.org/x/lint/golint
    - golint -set_exit_status ./...
  rules:
    # all branches
    - if: '$CI_COMMIT_BRANCH'
      # and merge requests
    - if: '$CI_MERGE_REQUEST_ID'

test:
  stage: test
  script:
    - go test -v ./...
  rules:
    # all branches
    - if: '$CI_COMMIT_BRANCH'
      # and merge requests
    - if: '$CI_MERGE_REQUEST_ID'


release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - goreleaser release --rm-dist
