name: test

on:
  push:
    branches: [ ** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubunntu-latest
    steps:
      - name: Prepare Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.6
        id: go

      - name: Checkout
        uses: actions/checkout-go@v2

      - name: Test
        run: go test ./...
